### ISSUE TITLE
if use on Windows

### ISSUE THREAD

**Issue by FayuanLi** [superscriptjs/sfacts#10]
## Expected Behavior

`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by bensalilijames** [comment]
`fsevents` is an optional dependency, it shouldn't matter if it's skipped on install on Windows, so you can ignore the warning. :)

If you run into any issues though, let us know!

**Comment by FayuanLi** [comment]
thanks for your replying
