### ISSUE TITLE
Allow option of mongodown - hosting leveldb in existing ss mongodb

### ISSUE THREAD

**Issue by Lewwwk** [superscriptjs/sfacts#3]
Because production environments often don't persist local files, it would be helpful to be able to pass the mongourl of the existing superscript mongo instance as the leveldb host.

I encountered this problem hosting on heroku and have heard reports of it being an issue with AWS as well.

**Comment by Lewwwk** [comment]
We have since set it up on an ec2, placing the facts directory in a shared folder so that we can be sure it persists across deploys. All is working well.

**Comment by bensalilijames** [comment]
Coming in v1.0.0.
